/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminLojasRouteImport } from './routes/admin.lojas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as CompraPurchaseIdRouteImport } from './routes/compra.$purchaseId'
import { Route as AdminUsuariosUserIdRouteImport } from './routes/admin.usuarios_.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const CompraPurchaseIdRoute = CompraPurchaseIdRouteImport.update({
  id: '/compra/$purchaseId',
  path: '/compra/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosUserIdRoute = AdminUsuariosUserIdRouteImport.update({
  id: '/usuarios_/$userId',
  path: '/usuarios/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios_/$userId': typeof AdminUsuariosUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bem-vindo'
    | '/historico'
    | '/lista'
    | '/login'
    | '/resumo'
    | '/scanner'
    | '/signup'
    | '/admin/categorias'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/compra/$purchaseId'
    | '/admin/'
    | '/admin/usuarios/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/historico'
    | '/lista'
    | '/login'
    | '/resumo'
    | '/scanner'
    | '/signup'
    | '/admin/categorias'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/compra/$purchaseId'
    | '/admin'
    | '/admin/usuarios/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bem-vindo'
    | '/historico'
    | '/lista'
    | '/login'
    | '/resumo'
    | '/scanner'
    | '/signup'
    | '/admin/categorias'
    | '/admin/lojas'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/compra/$purchaseId'
    | '/admin/'
    | '/admin/usuarios_/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BemVindoRoute: typeof BemVindoRoute
  HistoricoRoute: typeof HistoricoRoute
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  ResumoRoute: typeof ResumoRoute
  ScannerRoute: typeof ScannerRoute
  SignupRoute: typeof SignupRoute
  CompraPurchaseIdRoute: typeof CompraPurchaseIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/compra/$purchaseId': {
      id: '/compra/$purchaseId'
      path: '/compra/$purchaseId'
      fullPath: '/compra/$purchaseId'
      preLoaderRoute: typeof CompraPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios_/$userId': {
      id: '/admin/usuarios_/$userId'
      path: '/usuarios/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AdminUsuariosUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsuariosUserIdRoute: typeof AdminUsuariosUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsuariosUserIdRoute: AdminUsuariosUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BemVindoRoute: BemVindoRoute,
  HistoricoRoute: HistoricoRoute,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  ResumoRoute: ResumoRoute,
  ScannerRoute: ScannerRoute,
  SignupRoute: SignupRoute,
  CompraPurchaseIdRoute: CompraPurchaseIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
