/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as CompraPurchaseIdRouteImport } from './routes/compra.$purchaseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraPurchaseIdRoute = CompraPurchaseIdRouteImport.update({
  id: '/compra/$purchaseId',
  path: '/compra/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/lista': typeof ListaRoute
  '/resumo': typeof ResumoRoute
  '/scanner': typeof ScannerRoute
  '/compra/$purchaseId': typeof CompraPurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historico'
    | '/lista'
    | '/resumo'
    | '/scanner'
    | '/compra/$purchaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historico'
    | '/lista'
    | '/resumo'
    | '/scanner'
    | '/compra/$purchaseId'
  id:
    | '__root__'
    | '/'
    | '/historico'
    | '/lista'
    | '/resumo'
    | '/scanner'
    | '/compra/$purchaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  ListaRoute: typeof ListaRoute
  ResumoRoute: typeof ResumoRoute
  ScannerRoute: typeof ScannerRoute
  CompraPurchaseIdRoute: typeof CompraPurchaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra/$purchaseId': {
      id: '/compra/$purchaseId'
      path: '/compra/$purchaseId'
      fullPath: '/compra/$purchaseId'
      preLoaderRoute: typeof CompraPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  ListaRoute: ListaRoute,
  ResumoRoute: ResumoRoute,
  ScannerRoute: ScannerRoute,
  CompraPurchaseIdRoute: CompraPurchaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
